name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - pyproject.toml
      - .github/workflows/build-installer.yml

jobs:
  build-installer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .
      - name: Build installer with PyInstaller
        run: |
          pyinstaller --onefile --noconsole main.py
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinterest-board-downloader-installer
          path: dist/main.exe
